#Security Department work type @TODO -> replace it with another save repository and revert head to this commit, to save confidential data
apiVersion: /v1
kind: Secret
metadata:
  name: postgres-secret
type: Opaque
stringData:
  pg-user: "foxstudios"
  pg-db: "postgres"
  pg-password: "root"