#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  name: signaling-server-deployment
#spec:
#  selector:
#    matchLabels:
#      app: signaling-server
#  template:
#    metadata:
#      labels:
#        app: signaling-server
#    spec:
#      containers:
#        - name: signaling-server-pod
#          image: endienasg/webrtc-signaling-server
#          imagePullPolicy: Always
#          ports:
#            - containerPort: 8080
#---
#apiVersion: v1
#kind: Service
#metadata:
#  name: signaling-server-service
#  labels:
#    env: prod
#    owner: endienasg
#spec:
#  type: NodePort
#  selector:
#    app: signaling-server
#  ports:
#    - name: http
#      protocol: TCP
#      port: 5000
#      targetPort: 8080
#      nodePort: 30007
#---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgres
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              value: postgres
            - name: POSTGRES_USER
              value: foxstudios
            - name: POSTGRES_PASSWORD
              value: root
          volumeMounts:
            - mountPath: "/var/lib/postgresql/data"
              name: "mendix-pgdata"
      volumes:
        - hostPath:
            path: "/home/docker/pgdata"
          name: mendix-pgdata
  selector:
    matchLabels:
      app: postgres

---
apiVersion: v1
kind: Service
metadata:
  name: webrtc-db-service
spec:
  type: NodePort
  selector:
    app: postgres
  ports:
    - name: http
      protocol: TCP
      port: 5432
      targetPort: 5432
      nodePort: 30015
